
[colors.bright]
black = "#38252C"
blue = "#289cd5"
cyan = "#0a9b81"
green = "#76b639"
magenta = "#ff2491"
red = "#ff0000"
white = "#f8f8f8"
yellow = "#e1a126"

[colors.normal]
black = "#171717"
blue = "#16b1fb"
cyan = "#0fdcb6"
green = "#97d01a"
magenta = "#ff2491"
red = "#d81765"
white = "#ebebeb"
yellow = "#ffa800"

[font]
size = 14

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[window]
opacity = 1.0


